id = "vinilo"
name = "Vinilo"

root = "~/.local/opt/nodalix/apps/vinilo"
updater = "/usr/share/nodalix-apps/bin/nodalix-vinilo-update"
executable = "usr/bin/vinilo"

upstream = "https://github.com/danielmigueltejedor/vinilo"
update_strategy = "github-release"

channel = "stable"
build = "official-release"
integration = "nodalix"
