pragma Singleton
import QtQuick
import Quickshell.Io
import "."

// Keybindings for the shell's actions. Launcher defaults to SUPER+SPACE;
// other actions are unbound until assigned in Settings → Keybindings.
// Hyprland owns keybinds, so we generate binds.generated.lua from the saved
// combos and `hyprctl reload` to apply live. quickshell.lua sources that file
// and must not hardcode the same actions or Super+Space will fire twice.
QtObject {
    id: root

    // The bindable shell actions. `cmd` is run via hl.dsp.exec_cmd(...).
    readonly property var actions: [
        { key: "overview", label: I18n.tr("Window overview"), cmd: "nodalix-overview" },
        { key: "shortcuts", label: I18n.tr("Shortcut guide"), cmd: "qs -c nodalix ipc call shortcuts toggle" },
        { key: "launcher",   label: I18n.tr("App launcher"),      cmd: "qs -c nodalix ipc call launcher toggle" },
        { key: "settings",   label: I18n.tr("Settings"),          cmd: "qs -c nodalix ipc call settings toggle" },
        { key: "lock",       label: I18n.tr("Lock screen"),       cmd: "qs -c nodalix ipc call lock lock" },
        { key: "tools",      label: I18n.tr("Tools toolbar"),     cmd: "qs -c nodalix ipc call tools toggle" },
        { key: "scratchpad", label: I18n.tr("Scratchpad toggle"), cmd: "qs -c nodalix ipc call scratchpad toggle" }
    ]

    readonly property string _file: Paths.state("binds.generated.lua")

    function combo(k) { return SettingsService.get("binds." + k, k === "launcher" ? "SUPER + SPACE" : (k === "overview" ? "SUPER + TAB" : (k === "shortcuts" ? "SUPER + F1" : ""))) }
    function setCombo(k, v) {
        SettingsService.set("binds." + k, (v || "").trim())
        apply()
    }

    function _luaContent() {
        let out = [
            "-- AUTO-GENERATED by Quickshell Settings → Keybindings. Do not edit.",
            "-- Sourced by hypr/quickshell.lua. Unbound actions are omitted.",
            ""
        ]
        for (const a of actions) {
            const c = String(combo(a.key)).trim()
            if (c === "") continue
            out.push('hl.bind("' + c + '", hl.dsp.exec_cmd("' + a.cmd + '"))')
        }
        out.push("")
        return out.join("\n")
    }

    // Re-apply Hyprland config after the file is written, so binds take effect
    // without re-running autostart.
    property Process _reload: Process { command: ["hyprctl", "reload"] }

    property bool _pendingReload: false
    property Process _writer: Process {
        onExited: if (root._pendingReload) { root._reload.running = false; root._reload.running = true }
    }

    // doReload=true (a user edit) reloads Hyprland so the bind applies now;
    // false (startup sync) just refreshes the file for the next Hyprland start —
    // the persisted file was already sourced when Hyprland launched.
    function apply(doReload) {
        _pendingReload = (doReload !== false)
        _writer.command = ["sh", "-c", 'printf "%s" "$2" > "$1"', "_", root._file, root._luaContent()]
        _writer.running = false
        _writer.running = true
    }

    // Keep binds.generated.lua in sync with saved settings on every start, so
    // combos set in a prior session (or before the file moved to state) exist.
    Component.onCompleted: apply(false)
}
