#!/usr/bin/env python3
"""Persist and apply the Nodalix Hyprland window-layout profile."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


MODES = {"tiling", "scrolling", "tabs"}


def state_dir() -> Path:
    return Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state")) / "nodalix"


def lua_for(mode: str) -> str:
    header = "-- Generated by Nodalix Settings. Do not edit by hand.\n"
    common = """hl.config({
    binds = { scroll_event_delay = 180 },
    group = {
        auto_group = %s,
        group_on_movetoworkspace = %s,
        insert_after_current = true,
        groupbar = {
            enabled = true,
            blur = true,
            disable_when_only = true,
            font_size = 10,
            height = 24,
            indicator_height = 3,
            indicator_gap = 3,
            render_titles = true,
        },
    },
})
""" % ("true" if mode == "tabs" else "false", "true" if mode == "tabs" else "false")

    if mode == "scrolling":
        body = """hl.config({
    general = { layout = "scrolling" },
    scrolling = {
        direction = "right",
        column_width = 0.56,
        focus_fit_method = 1,
        follow_focus = true,
        follow_min_visible = 0.35,
        wrap_focus = true,
        wrap_swapcol = true,
        explicit_column_widths = "0.333, 0.5, 0.667, 1.0",
    },
})

-- A vertical wheel gesture changes workspaces; the windows themselves flow
-- horizontally, matching the Nodalix interpretation of a Niri-like desktop.
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + period", hl.dsp.layout("move +col"))
hl.bind("SUPER + comma", hl.dsp.layout("move -col"))
"""
    elif mode == "tabs":
        body = """hl.config({ general = { layout = "dwindle" } })

-- Hyprland groups are native i3-style tabbed containers. New windows join the
-- active unlocked group while this profile is selected.
hl.bind("SUPER + TAB", hl.dsp.group.next())
hl.bind("SUPER + SHIFT + TAB", hl.dsp.group.prev())
hl.bind("SUPER + G", hl.dsp.group.toggle())
"""
    else:
        body = """hl.config({ general = { layout = "dwindle" } })
"""
    return header + common + body


def apply(mode: str) -> int:
    if mode not in MODES:
        raise SystemExit(f"unsupported layout mode: {mode}")
    target_dir = state_dir()
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "layout.generated.lua"
    temporary = target.with_suffix(".tmp")
    temporary.write_text(lua_for(mode), encoding="utf-8")
    temporary.replace(target)
    (target_dir / "layout-mode").write_text(mode + "\n", encoding="utf-8")

    reload_result = subprocess.run(
        ["hyprctl", "reload"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        check=False,
    )
    if mode == "tabs" and reload_result.returncode == 0:
        # Start an unlocked group for the active window. If no regular window is
        # focused Hyprland safely treats the dispatcher as a no-op.
        subprocess.run(
            ["hyprctl", "dispatch", "togglegroup"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False,
        )
    return reload_result.returncode


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: nodalix-layout-mode tiling|scrolling|tabs", file=sys.stderr)
        return 2
    return apply(sys.argv[1])


if __name__ == "__main__":
    raise SystemExit(main())
