source = ~/.config/nodalix/hyprlock/theme.conf

general {
    ignore_empty_input = true
    hide_cursor = false
}

background {
    monitor =
    color = $color
    path = ~/.config/nodalix/backgrounds/current
    blur_passes = 4
    blur_size = 7
    noise = 0.012
    contrast = 0.92
    brightness = 0.62
    vibrancy = 0.18
    vibrancy_darkness = 0.35
}

animations {
    enabled = true
    bezier = nodalixEase, 0.22, 1, 0.36, 1
    animation = fade, 1, 4, nodalixEase
    animation = inputFieldDots, 1, 2, nodalixEase
}

# Hora principal
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgba(255, 255, 255, 0.96)
    font_size = 92
    font_family = Inter
    position = 0, 210
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.35)
}

# Fecha
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d de %B"
    color = $muted_color
    font_size = 18
    font_family = Inter
    position = 0, 140
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(0, 0, 0, 0.28)
}

# Marca Nodalix
label {
    monitor =
    text =   Nodalix OS
    color = $font_color
    font_size = 24
    font_family = JetBrainsMono Nerd Font Nodalix
    position = 0, 52
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 2
    shadow_color = rgba(0, 0, 0, 0.28)
}

# Subtítulo
label {
    monitor =
    text = Sesión bloqueada
    color = $muted_color
    font_size = 13
    font_family = Inter
    position = 0, 18
    halign = center
    valign = center
}

# Campo de contraseña estilo glass pill
input-field {
    monitor =
    size = 470, 58
    position = 0, -72
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 2

    font_family = Inter
    font_color = $font_color
    font_size = 15

    placeholder_text = <span foreground="##cdd6f4cc">Contraseña</span>
    check_color = $check_color
    fail_color = $fail_color
    fail_text = <span foreground="##f38ba8"><i>Contraseña incorrecta · intento $ATTEMPTS</i></span>

    dots_size = 0.28
    dots_spacing = 0.24
    dots_center = true

    rounding = 999
    shadow_passes = 2
    shadow_size = 8
    shadow_color = rgba(0, 0, 0, 0.32)
    fade_on_empty = false
}

# Ayuda inferior
label {
    monitor =
    text = Pulsa Esc para cancelar · Enter para desbloquear
    color = rgba(205, 214, 244, 0.55)
    font_size = 12
    font_family = Inter
    position = 0, -155
    halign = center
    valign = center
}

auth {
    fingerprint:enabled = false
}
