general {
    lock_cmd = nodalix-system-lock
    before_sleep_cmd = nodalix-system-lock
    after_sleep_cmd = nodalix-system-wake
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}

listener {
    timeout = 300
    on-timeout = nodalix-launch-screensaver
    on-resume = nodalix-system-wake
}

listener {
    timeout = 600
    on-timeout = nodalix-system-lock
    on-resume = nodalix-system-wake
}
